### ISSUE TITLE
Selecting protocol and market is not cached 

### ISSUE THREAD

**Issue by AdamGencel** [WeAreNewt/config.fyi#11]
When user selects protocol and market and then clicks on the "more info" link, and then goes back to the config.fyi app the previous protocol and market selection are not caches which forces user to select again. 

Not a big problem but would be a nic QOL if we could get that done
![Jun-02-2022 14-43-22](https://user-images.githubusercontent.com/42351914/171633460-adb55de5-cefb-4660-9331-face3dfff2bd.gif)

**Comment by 0xjim** [comment]
Great point. Let's cache, and also let's have the 'more info' button open to a new tab @arttu0
